#!/usr/bin/bash

PREFIX=~/local

export LD_LIBRARY_PATH=${PREFIX}/lib:${PREFIX}/usr/lib:${PREFIX}/usr/lib64:${PREFIX}/usr/libexec:${LD_LIBRARY_PATH}


for T in 01 03
do
	echo
	echo "Starting: $T"
	echo

	echo "checkmodule: mtest_attr_base_$T.mod"
	$PREFIX/usr/bin/checkmodule -M -o mtest_attr_base_$T.mod mtest_attr_base_$T.te

	echo "checkmodule: mtest_attr_mod1_$T.mod"
	$PREFIX/usr/bin/checkmodule -M -m -o mtest_attr_mod1_$T.mod mtest_attr_mod1_$T.te

	echo "checkmodule: mtest_attr_mod2_$T.mod"
	$PREFIX/usr/bin/checkmodule -M -m -o mtest_attr_mod2_$T.mod mtest_attr_mod2_$T.te

	echo "semodule_package: mtest_attr_base_$T.pp"
	$PREFIX/usr/bin/semodule_package -o mtest_attr_base_$T.pp -m mtest_attr_base_$T.mod

	echo "semodule_package: mtest_attr_mod1_$T.pp"
	$PREFIX/usr/bin/semodule_package -o mtest_attr_mod1_$T.pp -m mtest_attr_mod1_$T.mod

	echo "semodule_package: mtest_attr_mod2_$T.pp"
	$PREFIX/usr/bin/semodule_package -o mtest_attr_mod2_$T.pp -m mtest_attr_mod2_$T.mod

	echo "semodule_link: mtest_attr_$T.lnk"
	$PREFIX/usr/bin/semodule_link -o mtest_attr_$T.lnk mtest_attr_base_$T.pp mtest_attr_mod1_$T.pp mtest_attr_mod2_$T.pp

	echo "semodule_expand: mtest_attr_$T.bin"
	$PREFIX/usr/bin/semodule_expand -a mtest_attr_$T.lnk mtest_attr_$T.bin

	echo "checkpolicy: mtest_attr_$T.bin.conf"
	$PREFIX/usr/bin/checkpolicy -M -F -b -o mtest_attr_$T.bin.conf mtest_attr_$T.bin

	echo "hll: mtest_attr_base_$T.cil"
	$PREFIX/usr/libexec/selinux/hll/pp mtest_attr_base_$T.pp mtest_attr_base_$T.cil

	echo "hll: mtest_attr_mod1_$T.cil"
	$PREFIX/usr/libexec/selinux/hll/pp mtest_attr_mod1_$T.pp mtest_attr_mod1_$T.cil

	echo "hll: mtest_attr_mod2_$T.cil"
	$PREFIX/usr/libexec/selinux/hll/pp mtest_attr_mod2_$T.pp mtest_attr_mod2_$T.cil

	echo "secilc: mtest_attr_$T.cil.bin"
	$PREFIX/usr/bin/secilc -M 1 -o mtest_attr_$T.cil.bin mtest_attr_base_$T.cil mtest_attr_mod1_$T.cil mtest_attr_mod2_$T.cil

	echo "checkpolicy: mtest_attr_$T.cil.bin.conf"
	$PREFIX/usr/bin/checkpolicy -M -F -b -o mtest_attr_$T.cil.bin.conf mtest_attr_$T.cil.bin
done

for T in 02
do
	echo
	echo "Starting: $T [Expect this to end in an error]"
	echo
	echo "checkmodule: mtest_attr_base_$T.mod"
	$PREFIX/usr/bin/checkmodule -M -o mtest_attr_base_$T.mod mtest_attr_base_$T.te

	echo "checkmodule: mtest_attr_mod1_$T.mod"
	$PREFIX/usr/bin/checkmodule -M -m -o mtest_attr_mod1_$T.mod mtest_attr_mod1_$T.te

	echo "checkmodule: mtest_attr_mod2_$T.mod"
	$PREFIX/usr/bin/checkmodule -M -m -o mtest_attr_mod2_$T.mod mtest_attr_mod2_$T.te

	echo "semodule_package: mtest_attr_base_$T.pp"
	$PREFIX/usr/bin/semodule_package -o mtest_attr_base_$T.pp -m mtest_attr_base_$T.mod

	echo "semodule_package: mtest_attr_mod1_$T.pp"
	$PREFIX/usr/bin/semodule_package -o mtest_attr_mod1_$T.pp -m mtest_attr_mod1_$T.mod

	echo "semodule_package: mtest_attr_mod2_$T.pp"
	$PREFIX/usr/bin/semodule_package -o mtest_attr_mod2_$T.pp -m mtest_attr_mod2_$T.mod

	echo "semodule_link: mtest_attr_$T.lnk"
	$PREFIX/usr/bin/semodule_link -o mtest_attr_$T.lnk mtest_attr_base_$T.pp mtest_attr_mod1_$T.pp mtest_attr_mod2_$T.pp

	echo "semodule_expand: mtest_attr_$T.bin"
	$PREFIX/usr/bin/semodule_expand -a mtest_attr_$T.lnk mtest_attr_$T.bin

	echo "checkpolicy: mtest_attr_$T.bin.conf"
	$PREFIX/usr/bin/checkpolicy -M -F -b -o mtest_attr_$T.bin.conf mtest_attr_$T.bin

	echo "hll: mtest_attr_base_$T.cil"
	$PREFIX/usr/libexec/selinux/hll/pp mtest_attr_base_$T.pp mtest_attr_base_$T.cil

	echo "hll: mtest_attr_mod1_$T.cil"
	$PREFIX/usr/libexec/selinux/hll/pp mtest_attr_mod1_$T.pp mtest_attr_mod1_$T.cil

	echo "hll: mtest_attr_mod2_$T.cil"
	$PREFIX/usr/libexec/selinux/hll/pp mtest_attr_mod2_$T.pp mtest_attr_mod2_$T.cil

	echo "secilc: mtest_attr_$T.cil.bin"
	$PREFIX/usr/bin/secilc -M 1 -o mtest_attr_$T.cil.bin mtest_attr_base_$T.cil mtest_attr_mod1_$T.cil mtest_attr_mod2_$T.cil

	echo "checkpolicy: mtest_attr_$T.cil.bin.conf"
	$PREFIX/usr/bin/checkpolicy -M -F -b -o mtest_attr_$T.cil.bin.conf mtest_attr_$T.cil.bin
done

mv *.mod tmp/
mv *.pp tmp/
mv *.lnk tmp/
mv *.bin tmp/
mv *.cil tmp/
mv *.bin.conf tmp/
mv file_contexts tmp/
