#!/usr/bin/bash

PREFIX=~/local

export LD_LIBRARY_PATH=$PREFIX/lib:$PREFIX/usr/lib:$PREFIX/usr/lib64:$PREFIX/usr/libexec:${LD_LIBRARY_PATH}

for T in 01 03 05
do
	echo "test_$T"
	$PREFIX/usr/bin/checkpolicy -o test_$T.bin test_$T.conf
	$PREFIX/usr/bin/checkpolicy -F -b -o test_$T.bin.conf test_$T.bin
	mv test_$T.bin new/
	mv test_$T.bin.conf new/
	DR=`diff orig/test_$T.bin new/test_$T.bin | wc -l`
	if [ $DR != 0 ]
	then
		echo "orig/test_$T.bin and new/test_$T.bin are different"
	fi
	DR=`diff orig/test_$T.bin.conf new/test_$T.bin.conf | wc -l`
	if [ $DR != 0 ]
	then
		echo "orig/test_$T.bin.conf and new/test_$T.bin.conf are different"
	fi
done

for T in 02 04 06
do
	echo "test_$T"
	$PREFIX/usr/bin/checkpolicy -M -o test_$T.bin test_$T.conf
	$PREFIX/usr/bin/checkpolicy -F -b -M -o test_$T.bin.conf test_$T.bin
	mv test_$T.bin new/
	mv test_$T.bin.conf new/
	DR=`diff orig/test_$T.bin new/test_$T.bin | wc -l`
	if [ $DR != 0 ]
	then
		echo "orig/test_$T.bin and new/test_$T.bin are different"
	fi
	DR=`diff orig/test_$T.bin.conf new/test_$T.bin.conf | wc -l`
	if [ $DR != 0 ]
	then
		echo "orig/test_$T.bin.conf and new/test_$T.bin.conf are different"
	fi
done
