# Minimum policy.conf

class CLASS1
sid kernel
class CLASS1 { PERM1 }

default_range CLASS1 glblub;
#default_range CLASS1 target low-high;

sensitivity s01;
sensitivity s02;
sensitivity s03;

dominance { s01 s02 s03 }

category c01;
category c02;
category c03;

level s01:c01.c03;
level s02:c01.c03;
level s03:c01.c03;

mlsconstrain CLASS1 { PERM1 } ((h1 dom h2) and (l1 domby h1));
mlsvalidatetrans CLASS1 ((l1 eq l2) or (l1 incomp l2));

type TYPE1;
allow TYPE1 self : CLASS1 PERM1;
role auditadm_r;
role secadm_r;
role ROLE1;
role ROLE1 types TYPE1;
user USER1 roles ROLE1 level s01 range s01 - s03:c01.c03;
sid kernel USER1:ROLE1:TYPE1:s01
