# handle_unknown deny
class CLASS1
class cl1
class cl2
class cl3
sid kernel
class CLASS1 { PERM1 }
class cl1 { p1 }
class cl2 { p2 }
class cl3 { p3 }
sensitivity SENS1;
dominance { SENS1 }
level SENS1;
mlsconstrain CLASS1 { PERM1 } (h1 dom h2 and l1 domby h1);
type TYPE1;
type t1a;
type t2b;
type t3c;
type td1;
type td2;
type td3;
allow TYPE1 self:CLASS1 { PERM1 };
allow td2 t2b:cl2 { p2 };
allow td3 t3c:cl3 { p3 };
role ROLE1;
role r1a;
role r1b;
role r1c;
role r2a;
role r2b;
role r2c;
role r3a;
role r3b;
role r3c;
role rn1;
role rn2;
role rn3;
role ROLE1 types { TYPE1 };
role r1a types { t1a };
role r1b types { t1a };
role r1c types { t1a };
role r2a types { t2b };
role r2b types { t2b };
role r2c types { t2b };
role r3a types { t3c };
role r3b types { t3c };
role r3c types { t3c };
role_transition r1a t1a:cl1 rn1;
role_transition r1b t1a:cl1 rn1;
role_transition r1c t1a:cl1 rn1;
role_transition r2a t2b:cl2 rn2;
role_transition r2b t2b:cl2 rn2;
role_transition r2c t2b:cl2 rn2;
role_transition r3a t3c:cl3 rn3;
role_transition r3b t3c:cl3 rn3;
role_transition r3c t3c:cl3 rn3;
allow r1a rn1;
allow r1b rn1;
allow r1c rn1;
allow r2a rn2;
allow r2b rn2;
allow r2c rn2;
allow r3a rn3;
allow r3b rn3;
allow r3c rn3;
user USER1 roles ROLE1 level SENS1 range SENS1 - SENS1;
user us1a roles { r1a r1b r1c } level SENS1 range SENS1 - SENS1;
user us2b roles { r2a r2b r2c } level SENS1 range SENS1 - SENS1;
user us3c roles { r3a r3b r3c } level SENS1 range SENS1 - SENS1;
constrain cl1 { p1 } r1 == { r1a r1b r1c };
sid kernel USER1:ROLE1:TYPE1:SENS1 - SENS1
