# handle_unknown deny
class CLASS1
class cl1
class cl2
class cl3
sid kernel
class CLASS1 { PERM1 }
class cl1 { p1 }
class cl2 { p2 }
class cl3 { p3 }
sensitivity SENS1;
dominance { SENS1 }
level SENS1;
mlsconstrain CLASS1 { PERM1 } (h1 dom h2 and l1 domby h1);
attribute at1;
attribute at2;
attribute at3;
type TYPE1;
type t1a;
type t1b;
type t1c;
type t2a;
type t2b;
type t2c;
type t3a;
type t3b;
type t3c;
type td1;
type td2;
type td3;
typeattribute t1a at1;
typeattribute t1b at1;
typeattribute t1c at1;
typeattribute t2a at2;
typeattribute t2b at2;
typeattribute t2c at2;
typeattribute t3a at3;
typeattribute t3b at3;
typeattribute t3c at3;
allow TYPE1 self:CLASS1 { PERM1 };
allow td1 at1:cl1 { p1 };
allow td2 at2:cl2 { p2 };
allow td3 at3:cl3 { p3 };
role ROLE1;
role r1a;
role r2b;
role r3c;
role rn1;
role rn2;
role rn3;
role ROLE1 types { TYPE1 };
role r1a types { t1a t1b t1c };
role r2b types { t2a t2b t2c };
role r3c types { t3a t3b t3c };
role_transition r1a t1a:cl1 rn1;
role_transition r1a t1b:cl1 rn1;
role_transition r1a t1c:cl1 rn1;
role_transition r2b t2a:cl2 rn2;
role_transition r2b t2b:cl2 rn2;
role_transition r2b t2c:cl2 rn2;
role_transition r3c t3a:cl3 rn3;
role_transition r3c t3b:cl3 rn3;
role_transition r3c t3c:cl3 rn3;
user USER1 roles ROLE1 level SENS1 range SENS1 - SENS1;
constrain cl1 { p1 } t1 == at1;
sid kernel USER1:ROLE1:TYPE1:SENS1 - SENS1
