#!/usr/bin/bash

PREFIX=~/local

export LD_LIBRARY_PATH=$PREFIX/lib:$PREFIX/usr/lib:$PREFIX/usr/lib64:$PREFIX/usr/libexec:${LD_LIBRARY_PATH}


for T in 01
do
	echo "test_$T"
	$PREFIX/usr/bin/secilc -M 1 -Q -o test_$T.bin test_$T.cil
	$PREFIX/usr/bin/checkpolicy -M -C -b -o test_$T.bin.cil test_$T.bin
done

mv *.bin tmp/
mv *.bin.cil tmp/
mv file_contexts tmp/
