# handle_unknown deny
class CLASS1
sid kernel
sid security
sid unlabeled
sid UNKNOWN4
sid file
sid UNKNOWN6
sid init
sid any_socket
sid port
class CLASS1 { PERM1 }
sensitivity SENS1;
dominance { SENS1 }
level SENS1;
mlsconstrain CLASS1 { PERM1 } (h1 dom h2 and l1 domby h1);
type TYPE1;
type ty2;
type ty4;
type ty6;
type ty9;
allow TYPE1 self:CLASS1 { PERM1 };
role ROLE1;
role ROLE1 types { TYPE1 ty2 ty4 ty6 ty9 };
user USER1 roles ROLE1 level SENS1 range SENS1 - SENS1;
sid kernel USER1:ROLE1:TYPE1:SENS1 - SENS1
sid security USER1:ROLE1:ty2:SENS1 - SENS1
sid UNKNOWN4 USER1:ROLE1:ty4:SENS1 - SENS1
sid UNKNOWN6 USER1:ROLE1:ty6:SENS1 - SENS1
sid port USER1:ROLE1:ty9:SENS1 - SENS1
