class CLASS1
class cl1
class cl2
class cl3
class cl4
class cl5
class cl6

sid kernel

class CLASS1 { PERM1 }
class cl1 { p1 }
class cl2 { p2 }
class cl3 { p3 }
class cl4 { p4 }
class cl5 { p5 }
class cl6 { p6 }

sensitivity SENS1;
dominance { SENS1 }
level SENS1;
mlsconstrain CLASS1 { PERM1 } ((h1 dom h2) and (l1 domby h1));

attribute at1;
attribute at2;
attribute at3;
attribute at4;
attribute at5;
attribute at6;

type TYPE1;
type t1a;
type t1b;
type t1c;
type t2a;
type t2b;
type t2c;
type t3a;
type t3b;
type t3c;
type t4a;
type t4b;
type t4c;
type t5a;
type t5b;
type t5c;
type t6a;
type t6b;
type t6c;
type td1;
type td2;
type td3;
type td4;
type td5;
type td6;
type tx1;
type tx2;
type tx3;
type tx4;
type tx5;
type tx6;
type tn1;
type tn2;
type tn3;
type tn4;
type tn5;
type tn6;

typeattribute t1a at1;
typeattribute t1b at1;
typeattribute t1c at1;
typeattribute t2a at2;
typeattribute t2b at2;
typeattribute t2c at2;
typeattribute t3a at3;
typeattribute t3b at3;
typeattribute t3c at3;
typeattribute t4a at4;
typeattribute t4b at4;
typeattribute t4c at4;
typeattribute t5a at5;
typeattribute t5b at5;
typeattribute t5c at5;
typeattribute t6a at6;
typeattribute t6b at6;
typeattribute t6c at6;
typeattribute at1 at3;
#typeattribute at1 at5;
typeattribute at4 at2;
#typeattribute at6 at2;
typeattribute at3 at5;
typeattribute at6 at4;

allow TYPE1 self : CLASS1 PERM1;
allow td1 at1 : cl1 p1;
allow td2 at2 : cl2 p2;
allow td3 at3 : cl3 p3;
allow td4 at4 : cl4 p4;
allow td5 at5 : cl5 p5;
allow td6 at6 : cl6 p6;

type_transition at1 tx1 : cl1 tn1;
type_transition at2 tx2 : cl2 tn2;
type_transition at3 tx3 : cl3 tn3;
type_transition at4 tx4 : cl4 tn4;
type_transition at5 tx5 : cl5 tn5;
type_transition at6 tx6 : cl6 tn6;

role ROLE1;
role r1a;
role r2a;
role r3b;
role r4b;
role r5c;
role r6c;
role rn1;
role rn2;
role rn3;
role rn4;
role rn5;
role rn6;

role ROLE1 types TYPE1;
role r1a types at1;
role r2a types at2;
role r3b types at3;
role r4b types at4;
role r5c types at5;
role r6c types at6;
role rn1 types at1;
role rn2 types at2;
role rn3 types at3;
role rn4 types at4;
role rn5 types at5;
role rn6 types at6;

role_transition r1a at1 : cl1 rn1;
role_transition r2a at2 : cl2 rn2;
role_transition r3b at3 : cl3 rn3;
role_transition r4b at4 : cl4 rn4;
role_transition r5c at5 : cl5 rn5;
role_transition r6c at6 : cl6 rn6;

user USER1 roles ROLE1 level SENS1 range SENS1;

constrain cl1 { p1 } ((t1 == at1));
constrain cl2 { p2 } ((t1 == at2));

sid kernel USER1:ROLE1:TYPE1:SENS1
