class CLASS1
class cl1
class cl2

sid kernel

class CLASS1 { PERM1 }
class cl1 { p1 }
class cl2 { p2 }

sensitivity SENS1;
dominance { SENS1 }
level SENS1;
mlsconstrain CLASS1 { PERM1 } ((h1 dom h2) and (l1 domby h1));

attribute at1;
attribute at2;

type TYPE1;
type t1a;
type t2a;
type td0;
type tn0;
type tx0;

typeattribute t1a at1;
typeattribute t2a at2;
typeattribute at2 at1;

allow TYPE1 self : CLASS1 PERM1;
allow td0 at1 : cl1 p1;
allow td0 at2 : cl2 p2;

type_transition at1 tx0 : cl1 tn0;
type_transition at2 tx0 : cl2 tn0;

role ROLE1;
role r1a;
role r2a;
role rn1;
role rn2;

role ROLE1 types TYPE1;
role r1a types at1;
role r2a types at2;

role_transition r1a at1 : cl1 rn1;
role_transition r2a at2 : cl2 rn2;

user USER1 roles ROLE1 level SENS1 range SENS1;

constrain cl1 { p1 } ((t1 == at1));
constrain cl2 { p2 } ((t1 == at2));

sid kernel USER1:ROLE1:TYPE1:SENS1
