#!/usr/bin/bash

PREFIX=~/local

export LD_LIBRARY_PATH=${PREFIX}/lib:${PREFIX}/usr/lib:${PREFIX}/usr/lib64:${PREFIX}/usr/libexec:${LD_LIBRARY_PATH}


for T in 01
do
	echo "checkmodule: mtest_base_$T.mod"
	$PREFIX/usr/bin/checkmodule -M -o mtest_base_$T.mod mtest_base_$T.te

	echo "semodule_package: mtest_base_$T.pp"
	$PREFIX/usr/bin/semodule_package -o mtest_base_$T.pp -m mtest_base_$T.mod

	echo "hll: mtest_base_$T.cil"
	$PREFIX/usr/libexec/selinux/hll/pp mtest_base_$T.pp mtest_base_$T.cil

	echo "secilc: mtest_$T.cil.bin"
	$PREFIX/usr/bin/secilc -M 1 -o mtest_$T.cil.bin mtest_base_$T.cil

	#echo

	echo "checkpolicy: mtest_$T.cil.bin.conf"
	$PREFIX/usr/bin/checkpolicy -M -F -b -o mtest_$T.cil.bin.conf mtest_$T.cil.bin
done

mv *.mod tmp/
mv *.pp tmp/
mv *.bin tmp/
mv *.bin.conf tmp/
