# Attributes should not cause an implict bounds

class CLASS1
class CLASS2
class CLASS3
class CLASS4

sid kernel

class CLASS1 { PERM1A PERM1B }
class CLASS2 { PERM2A PERM2B }
class CLASS3 { PERM3A PERM3B }
class CLASS4 { PERM4A PERM4B }

sensitivity SENS1;
dominance { SENS1 }
level SENS1;
mlsconstrain CLASS1 { PERM1A } ((h1 dom h2) and (l1 domby h1));

attribute a1;
attribute a1.t;
attribute a2;
attribute ta3.t;

type TYPE1;
type a2.t; # "Type a2 is not declared"
type ta3;
type ta4;
type ta4.t;
type tx1;
type tx2;
type tx3;
type tx4;

allow TYPE1 self : CLASS1 PERM1A;

allow a1 tx1 : CLASS1 { PERM1A };
allow a1.t tx1 : CLASS1 { PERM1A PERM1B };

allow a2 tx2 : CLASS2 { PERM2A };
allow a2.t tx2 : CLASS2 { PERM2A PERM2B };

allow ta3 tx3 : CLASS3 { PERM3A };
allow ta3.t tx3 : CLASS3 { PERM3A PERM3B };

allow ta4 tx4 : CLASS4 { PERM4A };
#allow ta4.t tx4 : CLASS4 { PERM4A PERM4B }; # Child exceeds bounds of parent


role ROLE1;

role ROLE1 types TYPE1;

user USER1 roles ROLE1 level SENS1 range SENS1;

sid kernel USER1:ROLE1:TYPE1:SENS1
