# off-by-one error in cats_ebitmap_len

class CLASS1

sid kernel

class CLASS1 { PERM1 }

sensitivity SENS1;
dominance { SENS1 }
category CAT1;
category CAT2;
level SENS1:CAT1.CAT2;
mlsconstrain CLASS1 { PERM1 } (l1 == l2);

type TYPE1;

allow TYPE1 self : CLASS1 PERM1;

role ROLE1;

role ROLE1 types TYPE1;

user USER1 roles ROLE1 level SENS1 range SENS1 - SENS1:CAT1.CAT2;

sid kernel USER1:ROLE1:TYPE1:SENS1 - SENS1:CAT1.CAT2
