# Test scope

class CLASS1
sid SID1
class CLASS1 { PERM1 PERM2 PERM3 }
type TYPE1;
allow TYPE1 self : CLASS1 PERM1;
allow TYPE0 self : CLASS1 PERM1;
type TYPE0;

optional {
	require {
		type TYPE2;
	}
	allow TYPE2 self : CLASS1 PERM2;
}

optional {
	require {
		type TYPEX;
	}
	type TYPE2;
	allow TYPEX self : CLASS1 PERM2;
}

optional {
	require {
	 	 type TYPE3a;
	}
	allow TYPE3a self : CLASS1 PERM3;
}

optional {
	 require {
	 	 type TYPE3b;
	 }
	 type TYPE3a;
	 allow TYPE3b self : CLASS1 PERM3;
}

optional {
	require {
		type TYPEX;
	}
	type TYPE3b;
	allow TYPEX self : CLASS1 PERM3;
}

role ROLE1;
role ROLE1 types TYPE1;
user USER1 roles ROLE1;
sid SID1 USER1:ROLE1:TYPE1
