# Minimum policy.conf

# Can role statements use attributes, aliases, and sets?
# Yes.

class CLASS1
sid SID1
class CLASS1 { PERM1 }

attribute A1;
type TYPE1;
type TP1;
type TP2;
typealias TP2 alias TP2A;
typeattribute TP1 A1;

allow TYPE1 self : CLASS1 PERM1;

role ROLE1;
role RL1;
role RL2;
role ROLE1 types TYPE1;
role RL1 types { A1 TP2A };
role RL2 types { -TP2 };

user USER1 roles ROLE1;
sid SID1 USER1:ROLE1:TYPE1


