# Is a duplicate alias ok as long as it is for the same type? NO

class CLASS1
sid SID1
class CLASS1 { PERM1 }
type TYPE1;
type TYPE2;
typealias TYPE1 alias ALIAS1;
typealias TYPE2 alias ALIAS2;
#typealias TYPE1 alias ALIAS1;
allow TYPE1 self : CLASS1 PERM1;
allow ALIAS1 self : CLASS1 PERM1;
allow ALIAS2 self : CLASS1 PERM1;
role ROLE1;
role ROLE1 types TYPE1;
user USER1 roles ROLE1;
sid SID1 USER1:ROLE1:TYPE1
