# Test role and type attributes in constrain rule

class CLASS1
sid SID1
class CLASS1 { PERM1 }
attribute ta;
attribute_role ra;
type TYPE1;
type TYPE2;
typeattribute TYPE1 ta;
allow TYPE1 self : CLASS1 { PERM1 };
role ROLE1;
role ROLE1 types {TYPE1};
roleattribute ROLE1 ra;
user USER1 roles ROLE1;
constrain CLASS1 { PERM1 } (((u1 == {USER1}) or (r1 == ra)) or (t1 == { ta TYPE2 }));
sid SID1 USER1:ROLE1:TYPE1
