# Test alias and scope

class CLASS1
sid SID1
class CLASS1 { PERM1 PERM2 PERM3 }
type TYPE1;
allow TYPE1 self : CLASS1 PERM1;

type TYPE2a;
type TYPE2b;
type TYPE2c;
type TYPE2d;
typealias TYPE2d alias ALIAS2d;
type TYPE2e;
typealias TYPE2e alias ALIAS2e;

optional {
	require {
		type TYPE1;
	}
	allow TYPE1 self : CLASS1 PERM2;
}

optional {
	require {
		type TYPE2a;
	}
	allow TYPE2a self : CLASS1 PERM2;
}

optional {
	require {
		type TYPE2b;
	}
	allow TYPE2b self : CLASS1 PERM2;

	optional {
		require {
		 	type TYPE2c;
		}
		allow TYPE2c self : CLASS1 PERM2;
	}
}

optional {
	require {
		type ALIAS2d;
	}
	allow ALIAS2d self : CLASS1 PERM2;
}

optional {
	require {
	 	 type ALIAS2e;
	}
	allow ALIAS2e self : CLASS1 PERM3;
}

optional {
	 require {
	 	 class CLASS1 PERM3;
	 }
	 type TYPE3a;
}

optional {
	require {
		type TYPE3a;
	}
	allow TYPE3a self : CLASS1 PERM3;
}

optional {
	require {
		type TYPE3b;
	}
	allow TYPE3b self : CLASS1 PERM3;
}

optional {
	 require {
	 	 class CLASS1 PERM3;
	 }
	 type TYPE3b;
}

optional {
	 require {
	 	 class CLASS1 PERM3;
	 }
	 type TYPE3c;
	 typealias TYPE3c alias ALIAS3c;
}

optional {
	require {
		type ALIAS3c;
	}
	allow ALIAS3c self : CLASS1 PERM3;
}

optional {
	require {
		type ALIAS3d;
	}
	allow ALIAS3d self : CLASS1 PERM3;
}

optional {
	 require {
	 	 class CLASS1 PERM3;
	 }
	 type TYPE3d;
	 typealias TYPE3d alias ALIAS3d;
}


role ROLE1;
role ROLE1 types TYPE1;
user USER1 roles ROLE1;
sid SID1 USER1:ROLE1:TYPE1
