# Can use aliases, attributes, and lists in constraints

class CLASS1
sid SID1
class CLASS1 { PERM1 }
attribute A1;
type TYPE1;
type TYPE2;
type TYPE3;
type TYPE4;
typealias TYPE2 alias ALIAS2;
typeattribute TYPE1 A1;
typeattribute TYPE2 A1;
allow TYPE1 self : CLASS1 PERM1;
role ROLE1;
role ROLE1 types TYPE1;
user USER1 roles ROLE1;

constrain CLASS1 { PERM1 } ((t1 == A1) or (u1 == USER1));
constrain CLASS1 { PERM1 } ((t1 == ALIAS2) or (u1 == USER1));
constrain CLASS1 { PERM1 } ((t1 == { TYPE3 TYPE4 }) or (u1 == USER1));

# Negation not allowed in constraint
#constrain CLASS1 { PERM1 } ((t1 == { A1 -TYPE1 }) or (u1 == USER1));
# "~" not allowed
#constrain CLASS1 { PERM1 } ((t1 == ~A1) and (u1 == USER1));
# "*" not allowed
#constrain CLASS1 { PERM1 } ((t1 == *) and (u1 == USER1));

sid SID1 USER1:ROLE1:TYPE1
