# Test declaration in optional block

class CLASS1
sid SID1
class CLASS1 { PERM1 PERM2 PERM3 PERM4 PERM5 }
type TYPE0;
type TYPE1;
allow TYPE1 self : CLASS1 PERM1;
allow TYPE0 self : CLASS1 PERM1;

optional {
	require {
		type DNE;
	}
	#type TYPE0; # Error - Duplicate declaration
	allow TYPE0 DNE : CLASS1 PERM2;
}

optional {
	require {
		type TYPE2;
	}
	#type TYPE1; # Error - Duplicate declaration
	allow TYPE1 self : CLASS1 PERM3;
	allow TYPE2 self : CLASS1 PERM3;
}

optional {
	require {
	 	 type TYPE2;
	}
	type TYPE2;
	allow TYPE2 self : CLASS1 PERM4;
}

optional {
	 require {
	 	 type TYPE2;
	 }
	 #type TYPE2; # Error - Duplicate declaration
	 allow TYPE2 self : CLASS1 PERM5;
}

role ROLE1;
role ROLE1 types TYPE1;
user USER1 roles ROLE1;
sid SID1 USER1:ROLE1:TYPE1
