#!/usr/bin/bash

PREFIX=~/local

export LD_LIBRARY_PATH=$PREFIX/lib:$PREFIX/usr/lib:$PREFIX/usr/lib64:$PREFIX/usr/libexec:${LD_LIBRARY_PATH}

for T in 02
do
	echo "test_$T"
	$PREFIX/usr/bin/checkpolicy -M -o test_$T.bin test_$T.conf
	$PREFIX/usr/bin/checkpolicy -M -F -b -o test_$T.bin.conf test_$T.bin
done

mv *.bin tmp/
mv *.bin.conf tmp/
