# All policy.conf rules

class cl01
class cl02
class cl03
class cl04
class clx

sid kernel

common cm01 { p11a p11b }
common cm02 { p22a p22b }

class cl01 inherits cm01 { p01a p01b }
class cl02 inherits cm02
class cl03 { p03a p03b }
class cl04 { p04a p04b }
class clx { ioctl }


sensitivity s01;

dominance { s01 }

category c01;
category c02;
category c03;

level s01:c01.c03;

mlsconstrain cl01 { p01a } ((h1 dom h2) and (l1 domby h1));
mlsvalidatetrans cl03 ((l1 eq l2) or (l1 incomp l2));
mlsvalidatetrans cl03 ((l1 eq l2) or (t3 eq tp01));

type tp01;

allow tp01 self:cl01 { p01a };  

role rl01;

role rl01 types { tp01 };

user us01 roles rl01 level s01 range s01 - s01:c01.c03;

constrain cl01 { p01b } not ((t1 == tp01) and (u1 != u2));
validatetrans cl03 ((u1 == u2) or (r1 == r2));
validatetrans cl03 ((u1 == u2) or (t3 == tp01));

sid kernel us01:rl01:tp01:s01 - s01:c01.c03

fs_use_xattr fs01 us01:rl01:tp01:s01;
fs_use_task fs02 us01:rl01:tp01:s01;
fs_use_trans fs03 us01:rl01:tp01:s01;
genfscon fs04 / us01:rl01:tp01:s01
portcon udp 1000 us01:rl01:tp01:s01
portcon udp 1001-1009 us01:rl01:tp01:s01
portcon tcp 2000 us01:rl01:tp01:s01
portcon tcp 2001-2009 us01:rl01:tp01:s01
portcon dccp 3000 us01:rl01:tp01:s01
portcon dccp 3001-3009 us01:rl01:tp01:s01
netifcon if01 us01:rl01:tp01:s01 us01:rl01:tp01:s01
