# handle_unknown deny
class CLASS1
sid kernel
class CLASS1 { PERM1 PERM2 PERM3 }
type TYPE1;
type TYPE2a;
type TYPE2b;
type TYPE2c;
type TYPE2d;
type TYPE2e;
type TYPE3a;
type TYPE3b;
type TYPE3c;
type TYPE3d;
typealias TYPE2d alias ALIAS2d;
typealias TYPE2e alias ALIAS2e;
typealias TYPE3c alias ALIAS3c;
typealias TYPE3d alias ALIAS3d;
allow TYPE1 self:CLASS1 { PERM1 PERM2 };
allow TYPE2a self:CLASS1 { PERM2 };
allow TYPE2b self:CLASS1 { PERM2 };
allow TYPE2c self:CLASS1 { PERM2 };
allow TYPE2d self:CLASS1 { PERM2 };
allow TYPE2e self:CLASS1 { PERM3 };
allow TYPE3a self:CLASS1 { PERM3 };
allow TYPE3b self:CLASS1 { PERM3 };
allow TYPE3c self:CLASS1 { PERM3 };
allow TYPE3d self:CLASS1 { PERM3 };
role ROLE1;
role ROLE1 types { TYPE1 };
user USER1 roles ROLE1;
sid kernel USER1:ROLE1:TYPE1
