# handle_unknown deny
class CLASS1
class c1
class c2
class c3
sid kernel
class CLASS1 { PERM1 ioctl }
class c1 { p1a p1b p1c }
class c2 { p2a p2b p2c }
class c3 { p3a p3b p3c }
attribute b_a2;
attribute b_a2_c;
attribute b_a4;
attribute b_a4_c;
bool b_b1 false;
bool b_b2 false;
bool b_b3 false;
type TYPE1;
type b_t1;
type b_t1_c;
type b_t2;
type b_t2_c;
type b_ta;
type b_tb;
type b_tc;
type b_td;
type tx1;
type tx2;
type tx3;
type tx4;
type tx5;
type tx6;
type tx7;
type txr;
type txt;
typebounds b_t1 b_t1_c;
typebounds b_t2 b_t2_c;
typeattribute b_t2 b_a2;
typeattribute b_t2_c b_a2_c;
allow TYPE1 self:CLASS1 { PERM1 };
allow b_a2 b_ta:CLASS1 { PERM1 };
allow b_a2 b_tc:CLASS1 { PERM1 };
allow b_a2_c b_ta:CLASS1 { PERM1 };
allow b_a2_c b_td:CLASS1 { PERM1 };
allow b_t1 b_ta:CLASS1 { PERM1 };
allow b_t1 b_tc:CLASS1 { PERM1 };
allow b_t1 self:CLASS1 { PERM1 };
allow b_t1_c b_ta:CLASS1 { PERM1 };
allow b_t1_c b_td:CLASS1 { PERM1 };
allow b_t1_c self:CLASS1 { PERM1 };
allow b_t2 self:CLASS1 { PERM1 };
allow b_t2_c self:CLASS1 { PERM1 };
allow b_ta b_a2:CLASS1 { PERM1 };
allow b_ta b_a2_c:CLASS1 { PERM1 };
allow b_ta b_t1:CLASS1 { PERM1 };
allow b_ta b_t1_c:CLASS1 { PERM1 };
allow b_tc b_a2:CLASS1 { PERM1 };
allow b_tc b_t1:CLASS1 { PERM1 };
allow b_td b_a2_c:CLASS1 { PERM1 };
allow b_td b_t1_c:CLASS1 { PERM1 };
allowxperm tx1 txt:CLASS1 ioctl { 0x1234 };
if (b_b1) {
} else {
    allow b_a2 b_tb:CLASS1 { PERM1 };
    allow b_a2_c b_tb:CLASS1 { PERM1 };
    allow b_t1 b_tb:CLASS1 { PERM1 };
    allow b_t1_c b_tb:CLASS1 { PERM1 };
    allow b_tb b_a2:CLASS1 { PERM1 };
    allow b_tb b_a2_c:CLASS1 { PERM1 };
    allow b_tb b_t1:CLASS1 { PERM1 };
    allow b_tb b_t1_c:CLASS1 { PERM1 };
}
if (b_b2) {
} else {
    allow b_a2_c b_tc:CLASS1 { PERM1 };
    allow b_t1_c b_tc:CLASS1 { PERM1 };
    allow b_tc b_a2_c:CLASS1 { PERM1 };
    allow b_tc b_t1_c:CLASS1 { PERM1 };
}
if (b_b3) {
    allow b_a2 b_td:CLASS1 { PERM1 };
    allow b_t1 b_td:CLASS1 { PERM1 };
    allow b_td b_a2:CLASS1 { PERM1 };
    allow b_td b_t1:CLASS1 { PERM1 };
    type_transition tx3 txt:CLASS1 txr;
    type_member tx4 txt:CLASS1 txr;
    type_change tx5 txt:CLASS1 txr;
} else {
    allow b_a2 b_td:CLASS1 { PERM1 };
    allow b_t1 b_td:CLASS1 { PERM1 };
    allow b_td b_a2:CLASS1 { PERM1 };
    allow b_td b_t1:CLASS1 { PERM1 };
}
role ROLE1;
role rx1;
role rx2;
role ROLE1 types { TYPE1 };
role_transition rx1 txt:CLASS1 rx2;
allow rx1 rx2;
user USER1 roles ROLE1;
sid kernel USER1:ROLE1:TYPE1
