# handle_unknown deny
class CLASS1
sid kernel
class CLASS1 { PERM1 }
attribute ta;
type TYPE1;
type TYPE2;
typeattribute TYPE1 ta;
allow TYPE1 self:CLASS1 { PERM1 };
role ROLE1;
role ROLE1 types { TYPE1 };
user USER1 roles ROLE1;
constrain CLASS1 { PERM1 } ((u1 == USER1 or r1 == ROLE1) or t1 == { TYPE2 ta });
sid kernel USER1:ROLE1:TYPE1
