#!/usr/bin/bash


PREFIX=~/local

export LD_LIBRARY_PATH=${PREFIX}/lib:${PREFIX}/usr/lib:${PREFIX}/usr/lib64:${PREFIX}/usr/libexec:${LD_LIBRARY_PATH}


for T in 01 05 10 11 12 13 14 15 16 17 18
do
	$PREFIX/usr/bin/checkpolicy -F -b -o test_$T.bin.conf test_$T.bin
done

for T in 02 04 06 07
do
	$PREFIX/usr/bin/checkpolicy -F -b -M -o test_$T.bin.conf test_$T.bin
done

$PREFIX/usr/bin/checkpolicy -F -b -M -t xen -o test_03.bin.conf test_03.bin
